apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-virtual-host-ingress-green
spec:
  rules:
  - host: mynginx.apps.cluster-was-3953.was-3953.example.opentlc.com
    http:
      paths:
      - backend:
          serviceName: green-nginx-service
          servicePort: 8080