apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: green-nginx-subscription
  namespace: nginx-green
  annotations:
    apps.open-cluster-management.io/github-path: blueGreen/nginx/deployment
    apps.open-cluster-management.io/github-branch: blue-nginx
   #      apps.open-cluster-management.io/github-branch: green-nginx
  labels:
    app: nginx-deployment
spec:
  channel: demo/gitops
  placement:
    placementRef:
      name: nginx-deployment
      kind: PlacementRule
