apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ingress-nginx-subscription-green
  namespace: nginx-green
  labels:
    app: nginx-deployment
  annotations:
    apps.open-cluster-management.io/github-path: blueGreen/nginx/green-ingress
    apps.open-cluster-management.io/github-branch: blue-nginx
   # apps.open-cluster-management.io/github-branch: masterspec:
  channel: demo/gitops
  placement:
    placementRef:
      name: nginx-deployment
      kind: PlacementRule

